pipeline:
 
- tests:
    image: node:latest
    commands:
    - yarn install
    - yarn test

- publish: 
    image: plugins/docker
    dockerfile: Dockerfile
    repo: dunjjoye4real/react-invoicing
    auto_tag: true
    target: production
    secrets:
    - docker_username
    - docker_password

secrets:
  docker_username:
    external: 
      name: drone-drone#docker_username

  docker_password:
    external:
      name: drone-drone#docker_password
